### ISSUE TITLE
FASTQ from SRA not parsed by NeST

### ISSUE THREAD

**Issue by flashton2003** [shashidhar22/NeST#6]
I've installed NeST and the test run works. Now, I'm trying to run NeST on some CDC data which is publicly available (SRR7853847) and which I downloaded from SRA, but it's failing on prepInputs.
```
python3 ~/programs/NeST/nest.py -i public_data/fastqs/ -o public_data/output/ -a ~/programs/NeST/ref/pfalciparum/adapters.fa -r ~/programs/NeST/ref/pfalciparum/mdr.fa -b ~/programs/NeST/ref/pfalciparum/mdr.bed -m bowtie2 --varofint ref/pfalciparum/Reportable_SNPs.csv
2019-01-22 04:01:27,707 - NeST - INFO - Gathering input information from input path.
2019-01-22 04:01:27,712 - NeST.prepInputs - WARNING - Read from /home/ubuntu/public_data/fastqs/SRR7853847_2.fastq with header : @SRR7853847.1 1/2 does not follow any defined fastq header format.Please correct it
Traceback (most recent call last):
  File "/home/ubuntu/programs/NeST/nest.py", line 451, in <module>
    args.pic_path, args.voi_path, java_def, sra_def, args.verbose)
  File "/home/ubuntu/programs/NeST/nest.py", line 348, in marsBatch
    config = prep.prepInputs()
  File "/home/ubuntu/programs/NeST/nest/prepinputs.py", line 304, in prepInputs
    experiment[sample] = Sample(sample, lib, seqType,
UnboundLocalError: local variable 'lib' referenced before assignment
```

From a comparison of fastq headers of the working sample and the failing sample, I would guess that it is having a problem with the slash in the header?

Working:
`@SRR6463548.1 1 length=65`
Failing:
`@SRR7853847.1 1/2`

**Comment by shashidhar22** [comment]
Thank you for bringing the issue to light. Yes, a part of the NeST tries to identify the library type of the input based on the Fastq header. Over the years SRA has changed their header formats, and looks like this sample number has a format that's not accounted for in the regex used by NeST. I will push a fix soon

**Comment by eldin-talundzic** [comment]
Hmm.. Shashi, you think this is a potential point of failure (PoF) since if there is another change in the future it will break the pipeline. Could it be an “optional flag” to run the pre-inputs as a work around to determine the library type?

Kind regards,

Eldin
_____________________________________________

Eldin Talundzic, Ph.D.

Health Scientist (Informatics)  | DPDM AMD Laboratory
Center for Disease Control and Prevention |
Division of Parasitic Diseases and Malaria (DPDM)
DDPHSIS/Center for Global Health (CGH)

1600 Clifton Rd, Atlanta, GA 30329
M: 706.363.2226 | W: 404.718.4403
etalundzic@cdc.gov<mailto:etalundzic@cdc.gov>


[cid:88de8bc4-8dd9-44db-b30b-6690b59cc686@cdc.gov]

On Jan 22, 2019, at 10:31 AM, Shashidhar Ravishankar <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you for bringing the issue to light. Yes, a part of the NeST tries to identify the library type of the input based on the Fastq header. Over the years SRA has changed their header formats, and looks like this sample number has a format that's not accounted for in the regex used by NeST. I will push a fix soon

**Comment by shashidhar22** [comment]
Yeah it can be made an optional field, adding an escape clause to the library check step can any failure due to changes to the header format in the future

**Comment by shashidhar22** [comment]
@flashton2003 I am trying to recreate the error on my end. But when I pull down SRR7853847 using SRA toolkit, I see that the header is in the standard SRA format i.e,
``` @SRR6463547.1 1 length=101 ```

Can you point me to where you downloaded the files for SRR7853847 from?

**Comment by flashton2003** [comment]
I can't find out which sra-toolkit version I used to originally download the FASTQ, and now v2.9.2 is downloading in the correct format. Sorry about that!

I'm a bioinformatician at Oxford University Clinical Research Unit in Ho Chi Minh City. One of my colleagues in the malaria group wants to use NeST/MaRS.

**Comment by shashidhar22** [comment]
No problem, that needed to be addressed in case some was using older files. The issue has been fixed with the latest commit, can let me know if you are running into the same issue?

**Comment by shashidhar22** [comment]
@flashton2003  can I go ahead and close this issue?

**Comment by flashton2003** [comment]
Yes, thank you.
